import {randomUUID} from 'node:crypto';
import {state,progress,upload,finish,fail,removeSnapshot} from './store.js';
const LF='id Lead_ID Full_Name Mobile Email Region City State1 Lead_Source Created_Time Owner Current_Owner_Name Previous_Owner_Name Sales_Manager Lead_Assigned_Date Lead_Status Project_Stage Lead_Disposition Priority Priority_Type Follow_up_Priority Follow_Up_Date Follow_Up_Date_Time Follow_Up_Type Final_Date_Time Visit_Call_Date_Time Last_Activity_Time Converted__s Converted_Date_Time Total_Calls Call_Duration Incoming_Calls Outgoing_Calls Missed_Calls_Count Client_Status Teams Lead_Type Assign_Type Modified_Time Company Last_Note'.split(' ');
const CF='id Owner What_Id Call_Type Call_Result Call_Start_Time Call_Duration_in_seconds Outgoing_Call_Status Created_By Call_Purpose Subject Created_Time Who_Id'.split(' ');
export class CRM{
 async token(){const r=await fetch('https://accounts.zoho.in/oauth/v2/token',{method:'POST',body:new URLSearchParams({client_id:process.env.PSM_CRM_CLIENT_ID,client_secret:process.env.PSM_CRM_CLIENT_SECRET,refresh_token:process.env.PSM_CRM_REFRESH_TOKEN,grant_type:'refresh_token'}),signal:AbortSignal.timeout(45000)});const j=await r.json();if(!j.access_token)throw new Error('Zoho authentication failed');this.t=j.access_token;}
 async request(path,query){if(!this.t)await this.token();for(let i=0;i<5;i++){let r;try{r=await fetch('https://www.zohoapis.in/crm/v8/'+path,{method:query?'POST':'GET',headers:{Authorization:'Zoho-oauthtoken '+this.t,'Content-Type':'application/json'},body:query?JSON.stringify({select_query:query}):undefined,signal:AbortSignal.timeout(70000)});}catch{if(i===4)throw new Error('Zoho connection failed');await new Promise(r=>setTimeout(r,2000));continue;}if(r.status===204)return {};if(r.status===401&&i===0){await this.token();continue;}if(r.status===429||r.status>=500){await new Promise(r=>setTimeout(r,3000*(i+1)));continue;}const j=await r.json();if(!r.ok)throw new Error('Zoho '+r.status+' '+(j.code||'API_ERROR'));return j;}throw new Error('Zoho retry limit reached');}
 async scan(module,fields,condition){let last='0',out=[];while(true){const where=condition?`(id > ${last} and (${condition}))`:`id > ${last}`;const r=await this.request('coql',`select ${fields.join(', ')} from ${module} where ${where} order by id asc limit 2000`);const rows=r.data||[];if(!rows.length)break;if(BigInt(rows.at(-1).id)<=BigInt(last))throw new Error('CRM pagination failed');out.push(...rows);last=rows.at(-1).id;await progress(`Fetching ${module}: ${out.length.toLocaleString('en-IN')} records`);if(!r.info?.more_records)break;}if(new Set(out.map(r=>r.id)).size!==out.length)throw new Error('Duplicate CRM record IDs');return out;}
}
export async function run(){try{
 const c=new CRM(),org=await c.request('org');if(!org.org?.some(o=>String(o.zgid)==='60038775297'))throw new Error('CRM organisation mismatch');
 const leads=await c.scan('Leads',LF),converted=[];let page=1,token;
 while(true){const p=new URLSearchParams({fields:LF.slice(1).join(','),converted:'true',per_page:'200',...(token?{page_token:token}:{page:String(page)})});const r=await c.request('Leads?'+p);converted.push(...(r.data||[]));await progress(`Fetching converted Leads: ${converted.length}`);if(!r.info?.more_records)break;token=r.info.next_page_token;page++;if(!token&&page>10)throw new Error('Converted lead pagination token missing');}
 const lm=new Map(leads.map(r=>[r.id,r]));for(const r of converted){r.Converted__s=true;lm.set(r.id,r);}const all=[...lm.values()],calls=await c.scan('Calls',CF);
 const deals=await c.scan('Deals',['id','Mobile','Stage','Modified_Time']);const history=await c.scan('DealHistory',['id','Potential_Name','Stage','Moved_To__s'],"Stage = 'Raw Quote' or Moved_To__s = 'Raw Quote'");
 if(!all.length||!calls.length)throw new Error('Empty CRM extract; previous snapshot retained');
 const users={...((await state()).manifest?.users||{})};for(const r of [...all,...calls])for(const k of ['Owner','Sales_Manager','Created_By'])if(r[k]?.name)users[r[k].id]=r[k].name;for(const r of all)if(r.Current_Owner_Name&&r.Owner)users[r.Owner.id]=r.Current_Owner_Name;
 const value=(r,k)=>{const v=r[k];if(k==='Converted__s')return !!v;if(v&&typeof v==='object')return v.id||null;if(typeof v==='string'&&/^\d{4}-\d\d-\d\dT/.test(v))return v.slice(0,19);return v===''||v==null?null:v;};
 const lr=all.map(r=>LF.map(k=>value(r,k)));const cr=calls.map(r=>{const a=CF.slice(0,-1).map(k=>value(r,k));a[2]=value(r,'What_Id')||value(r,'Who_Id');return a;});
 const mob=v=>{const d=String(v||'').replace(/\D/g,'');return d.length>=10?d.slice(-10):null;};const byid=new Map(deals.map(d=>[d.id,d]));const raw=[...new Set(history.map(h=>mob(byid.get(h.Potential_Name?.id)?.Mobile)).filter(Boolean))];const stages={};for(const d of deals.sort((a,b)=>(a.Modified_Time||'').localeCompare(b.Modified_Time||''))){const m=mob(d.Mobile);if(m&&d.Stage)stages[m]=d.Stage;}
 const id=randomUUID();const stamp=new Date().toLocaleString('sv-SE',{timeZone:'Asia/Kolkata'}).replace(' ','T')+'+05:30';const meta={generatedAt:stamp,lastFull:stamp,supplementaryGeneratedAt:stamp,snapshotId:id,leadCount:lr.length,callCount:cr.length,convertedLeadCount:converted.length,crmBase:'https://crm.zoho.in/crm/org60038775297/tab',orgId:'60038775297',source:'Zoho CRM',users};
 await progress('Publishing completed CRM snapshot');for(const [n,d] of [['leads',lr],['calls',cr],['rawquote',raw],['dealstage',stages]])await upload(id,n,d);const prior=(await state()).manifest;meta.previousSnapshotId=prior?.snapshotId;await finish(meta);if(prior?.previousSnapshotId)await removeSnapshot(prior.previousSnapshotId).catch(()=>{});
 }catch(e){await fail(e.message);}}
