import pg from 'pg';
const databaseUrl=new URL(process.env.POSTGRES_URL);
for(const key of ['sslmode','sslcert','sslkey','sslrootcert'])databaseUrl.searchParams.delete(key);
export const pool=new pg.Pool({connectionString:databaseUrl.toString(),max:3,ssl:{rejectUnauthorized:false}});
const BUCKET='psm-live-snapshots';
export async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS psm_dashboard_sync_v1 (id int primary key, manifest jsonb, status jsonb not null default '{}', lease_until timestamptz, last_started timestamptz)`);await pool.query(`ALTER TABLE psm_dashboard_sync_v1 ENABLE ROW LEVEL SECURITY`);await pool.query(`INSERT INTO psm_dashboard_sync_v1(id) VALUES(1) ON CONFLICT DO NOTHING`);}
export async function state(){const {rows}=await pool.query('SELECT * FROM psm_dashboard_sync_v1 WHERE id=1');return rows[0];}
export async function acquire({scheduled=false,trigger='manual'}={}){const {rowCount}=await pool.query(`UPDATE psm_dashboard_sync_v1 SET lease_until=now()+interval '14 minutes',last_started=now(),status=$1 WHERE id=1 AND (lease_until IS NULL OR lease_until<now()) AND (last_started IS NULL OR last_started<now()-interval '60 seconds') AND ($2::boolean=false OR ((manifest IS NULL OR (manifest->>'generatedAt')::timestamptz<=now()-interval '15 minutes') AND (status->>'state' IS DISTINCT FROM 'error' OR COALESCE((status->>'failedAt')::timestamptz,'-infinity'::timestamptz)<=now()-interval '2 minutes')))`,[JSON.stringify({state:'running',message:'Connecting to Zoho CRM',startedAt:new Date().toISOString(),trigger}),scheduled]);return rowCount===1;}
export async function progress(message){await pool.query(`UPDATE psm_dashboard_sync_v1 SET status=status || $1::jsonb WHERE id=1`,[JSON.stringify({message})]);}
export async function finish(meta){await pool.query(`UPDATE psm_dashboard_sync_v1 SET manifest=$1,status=status || $2::jsonb,lease_until=NULL WHERE id=1`,[JSON.stringify(meta),JSON.stringify({state:'complete',message:'CRM sync complete',error:null,lastSuccess:meta.generatedAt,leadCount:meta.leadCount,callCount:meta.callCount})]);}
export async function fail(message){await pool.query(`UPDATE psm_dashboard_sync_v1 SET status=status || $1::jsonb,lease_until=NULL WHERE id=1`,[JSON.stringify({state:'error',message,error:message,failedAt:new Date().toISOString()})]);}
async function storage(path,options={}){const r=await fetch(process.env.SUPABASE_URL+'/storage/v1/'+path,{...options,headers:{Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,...options.headers},signal:AbortSignal.timeout(120000)});if(!r.ok)throw new Error('Snapshot storage request failed ('+r.status+')');return r;}
export async function initBucket(){try{await storage('bucket/'+BUCKET);}catch{await storage('bucket',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:BUCKET,name:BUCKET,public:false,file_size_limit:52428800})});}}
export async function upload(id,name,data){await storage('object/'+BUCKET+'/'+id+'/'+name+'.json',{method:'POST',headers:{'Content-Type':'application/json','x-upsert':'true'},body:JSON.stringify(data)});}
export async function signed(id,file){const r=await storage('object/sign/'+BUCKET+'/'+id+'/'+file,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn:120})});const j=await r.json();return process.env.SUPABASE_URL+'/storage/v1'+j.signedURL;}
export async function removeSnapshot(id){if(!id||!/^[a-zA-Z0-9-]{1,64}$/.test(id))return;await storage('object/'+BUCKET,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefixes:['leads','calls','rawquote','dealstage'].map(n=>id+'/'+n+'.json')})});}
